SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((B.PRICE * S.SALES)) TOTAL_SALES
FROM BOOK_SALES S
JOIN BOOK B ON B.BOOK_ID = S.BOOK_ID
JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) =1
GROUP BY B.CATEGORY, A.AUTHOR_ID
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC

# -- 코드를 입력하세요
# SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(S.SALES *B.PRICE) TOTAL_SALES
# FROM BOOK_SALES S
# JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
# JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
# GROUP BY CATEGORY, AUTHOR_ID
# ORDER BY A.AUTHOR_ID, CATEGORY DESC

# SELECT A.AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM((SALES * PRICE)) AS TOTAL_SALES
# FROM BOOK_SALES S
# JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID
# JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
# WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
# GROUP BY CATEGORY, AUTHOR_ID
# ORDER BY A.AUTHOR_ID, CATEGORY DESC